In [1]:
# import the NumPy and csv modules
import numpy as np
import csv

# Creating a 1D ndarray

---

In [2]:
data_ndarray = np.array([10, 20, 30])
type(data_ndarray)

numpy.ndarray

# Read in csv as a list of lists

---

In [29]:
# remove scientific notation from array results
np.set_printoptions(precision=2, suppress=True)

In [30]:
import csv
import numpy as np

# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

taxi = np.array(converted_taxi_list)
taxi

array([[2016.  ,    1.  ,    1.  , ...,   11.65,   69.99,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    8.  ,   54.3 ,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    0.  ,   37.8 ,    2.  ],
       ...,
       [2016.  ,    6.  ,   30.  , ...,    5.  ,   63.34,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    8.95,   44.75,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    0.  ,   54.84,    2.  ]])

In [5]:
# find the number of rows and columns with the .shape attribute
taxi_shape = taxi.shape
print(taxi_shape)

(30195, 15)


In [7]:
row_0 = taxi[0]
rows_391_to_500 = taxi[391:501]
row_21_column_5 = taxi[21][5]

In [31]:
cols = [1,4,7]
columns_1_4_7 = taxi[:, cols]
print(columns_1_4_7)

row_99_columns_5_to_8 = taxi[99,5:9]
print(row_99_columns_5_to_8)

rows_100_to_200_column_14 = taxi[100:201,14]
print(rows_100_to_200_column_14)

[[ 1.    0.   21.  ]
 [ 1.    0.   16.29]
 [ 1.    0.   12.7 ]
 ...
 [ 6.    5.   17.48]
 [ 6.    5.   12.76]
 [ 6.    5.   17.54]]
[   2.      4.     20.91 1744.  ]
[2. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 2. 2. 2. 1. 2. 1. 2. 1. 1. 2. 2.
 2. 1. 1. 2. 1. 2. 1. 1. 2. 2. 1. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 2. 2. 2.
 2. 2. 1. 4. 2. 1. 2. 1. 2. 2. 2. 2. 1. 1. 2. 1. 2. 2. 2. 2. 1. 2. 2. 1.
 2. 1. 2. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 2. 2. 1. 1. 2. 1. 1.
 1. 1. 1. 2. 2.]


In [32]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]

fare_and_fees = fare_amount + fees_amount
print(fare_and_fees)

[52.8 46.3 37.8 ... 52.8 35.8 49.3]


In [33]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

trip_mph = trip_distance_miles / trip_length_hours

In [34]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

print(mph_min.round(), mph_max.round(), mph_mean.round())

0.0 82800.0 170.0


In [35]:
print(taxi[:,9:13])

[[52.    0.8   5.54 11.65]
 [45.    1.3   0.    8.  ]
 [36.5   1.3   0.    0.  ]
 ...
 [52.    0.8   5.54  5.  ]
 [34.5   1.3   0.    8.95]
 [48.    1.3   5.54  0.  ]]


In [36]:
# we'll compare against the first 5 rows only
taxi_first_five = taxi[:5]
# select these columns: fare_amount, fees_amount, tolls_amount, tip_amount
fare_components = taxi_first_five[:,9:13]

fare_sums = fare_components.sum(axis=1)
print(fare_sums)

fare_totals = taxi_first_five[:,13]
print(fare_totals)
print(fare_sums)

[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]
